// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFvs7iguclQswi3gBzKQzOVfbvu5hNKVk',
    appId: '1:425924821182:web:c176712d302e79c20a5eef',
    messagingSenderId: '425924821182',
    projectId: 'chat-room-app-1995',
    authDomain: 'chat-room-app-1995.firebaseapp.com',
    storageBucket: 'chat-room-app-1995.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEQBEYoQ6Hva-3ZogvM3bx_5P9klc4KJ4',
    appId: '1:425924821182:android:55c80746c533333e0a5eef',
    messagingSenderId: '425924821182',
    projectId: 'chat-room-app-1995',
    storageBucket: 'chat-room-app-1995.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6KLAJ2RPm0UwOZDXW8VdJ1npQ4KeGgNs',
    appId: '1:425924821182:ios:d4192d6f041cf50b0a5eef',
    messagingSenderId: '425924821182',
    projectId: 'chat-room-app-1995',
    storageBucket: 'chat-room-app-1995.firebasestorage.app',
    iosBundleId: 'com.example.desafioCloudFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6KLAJ2RPm0UwOZDXW8VdJ1npQ4KeGgNs',
    appId: '1:425924821182:ios:d4192d6f041cf50b0a5eef',
    messagingSenderId: '425924821182',
    projectId: 'chat-room-app-1995',
    storageBucket: 'chat-room-app-1995.firebasestorage.app',
    iosBundleId: 'com.example.desafioCloudFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFvs7iguclQswi3gBzKQzOVfbvu5hNKVk',
    appId: '1:425924821182:web:8aada30cb3f304790a5eef',
    messagingSenderId: '425924821182',
    projectId: 'chat-room-app-1995',
    authDomain: 'chat-room-app-1995.firebaseapp.com',
    storageBucket: 'chat-room-app-1995.firebasestorage.app',
  );

}